on:
  push:
    paths:
      - src/**
      - build.gradle
      - common.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup java ${{ matrix.java }}
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Setup cache
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: versions/*/build/libs/
